"""
Generated State Machine: BDBOStrategy
Namespace: Trading.Strategies

Generated by SMCG. Do not edit manually.
"""

from __future__ import annotations

from enum import IntEnum
from typing import Any, Optional

from jgtutils.statemachine.runtime import (
    Context,
    ContextAsync,
    ContextBase,
    ObserverNull,
    State,
    StateKind,
    TransitionHelper,
)

class BDBOStrategyStateEnum(IntEnum):
    """State enumeration for BDBOStrategy."""
    ROOT = 0
    IDLE = 1
    ACTIVE = 2
    ACTIVE_WAITING_BREAKOUT = 3
    ACTIVE_WAITING_SIGNAL = 4
    ACTIVE_WAITING_ENTRY = 5
    COMPLETED = 6
    FAILED = 7

class StateBDBOStrategy(State):
    """Base state with virtual event handlers for BDBOStrategy."""

    def on_strategy_created(self, context, strategy_id: str) -> None:
        pass

    def on_price_breakout(self, context, price: float, direction: str) -> None:
        pass

    def on_signal_found(self, context) -> None:
        pass

    def on_order_filled(self, context) -> None:
        pass

    def on_strategy_completed(self, context) -> None:
        pass

    def on_strategy_failed(self, context) -> None:
        pass

    def on_ev_timeout(self, context, source: Any) -> None:
        pass


class StateIdle(StateBDBOStrategy):
    """State: Idle"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Idle", kind=StateKind.LEAF, parent=parent)

    def on_strategy_created(self, context, strategy_id: str) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_active_waiting_breakout, "StrategyCreated"
        )
        context.state_current = context.state_active_waiting_breakout
        TransitionHelper.process_transition_end(
            context, self, context.state_active_waiting_breakout
        )


class StateActiveWaitingBreakout(StateBDBOStrategy):
    """State: Active_WaitingBreakout"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Active_WaitingBreakout", kind=StateKind.LEAF, parent=parent)

    def on_entry(self, context: ContextBase) -> None:
        context.strategy.start_monitoring()

    def on_price_breakout(self, context, price: float, direction: str) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_active_waiting_signal, "PriceBreakout"
        )
        context.state_current = context.state_active_waiting_signal
        TransitionHelper.process_transition_end(
            context, self, context.state_active_waiting_signal
        )

    def on_strategy_failed(self, context) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_failed, "StrategyFailed"
        )
        context.state_current = context.state_failed
        TransitionHelper.process_transition_end(
            context, self, context.state_failed
        )


class StateActiveWaitingSignal(StateBDBOStrategy):
    """State: Active_WaitingSignal"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Active_WaitingSignal", kind=StateKind.LEAF, parent=parent)

    def on_entry(self, context: ContextBase) -> None:
        context.start_timer("Timeout", 60000, lambda: context.on_timeout())

    def on_exit(self, context: ContextBase) -> None:
        context.stop_timer("Timeout")

    def on_signal_found(self, context) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_active_waiting_entry, "SignalFound"
        )
        context.state_current = context.state_active_waiting_entry
        TransitionHelper.process_transition_end(
            context, self, context.state_active_waiting_entry
        )

    def on_ev_timeout(self, context, source: Any) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_active_waiting_breakout, "evTimeout"
        )
        context.state_current = context.state_active_waiting_breakout
        TransitionHelper.process_transition_end(
            context, self, context.state_active_waiting_breakout
        )


class StateActiveWaitingEntry(StateBDBOStrategy):
    """State: Active_WaitingEntry"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Active_WaitingEntry", kind=StateKind.LEAF, parent=parent)

    def on_order_filled(self, context) -> None:
        TransitionHelper.process_transition_begin(
            context, self, context.state_completed, "OrderFilled"
        )
        context.state_current = context.state_completed
        TransitionHelper.process_transition_end(
            context, self, context.state_completed
        )

    def on_strategy_failed(self, context) -> None:
        if strategy.can_retry():
            TransitionHelper.process_transition_begin(
                context, self, context.state_active_waiting_signal, "StrategyFailed[strategy.can_retry()]"
            )
            context.state_current = context.state_active_waiting_signal
            TransitionHelper.process_transition_end(
                context, self, context.state_active_waiting_signal
            )
        else:
            TransitionHelper.process_transition_begin(
                context, self, context.state_failed, "StrategyFailed"
            )
            context.state_current = context.state_failed
            TransitionHelper.process_transition_end(
                context, self, context.state_failed
            )


class StateCompleted(StateBDBOStrategy):
    """State: Completed"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Completed", kind=StateKind.FINAL, parent=parent)


class StateFailed(StateBDBOStrategy):
    """State: Failed"""

    def __init__(self, parent: Optional[State] = None):
        super().__init__(name="Failed", kind=StateKind.FINAL, parent=parent)


class BDBOStrategyContext(Context):
    """Context for BDBOStrategy state machine."""

    def __init__(self, strategy: BDBOStrategyEntity):
        super().__init__(name="BDBOStrategyContext")
        self.strategy = strategy

        # Initialize states
        self.state_root = State(name="Root", kind=StateKind.ROOT, parent=None)
        self.state_active = State(name="Active", kind=StateKind.COMPOSITE, parent=self.state_root)
        self.state_idle = StateIdle(parent=self.state_root)
        self.state_active_waiting_breakout = StateActiveWaitingBreakout(parent=self.state_active)
        self.state_active_waiting_signal = StateActiveWaitingSignal(parent=self.state_active)
        self.state_active_waiting_entry = StateActiveWaitingEntry(parent=self.state_active)
        self.state_completed = StateCompleted(parent=self.state_root)
        self.state_failed = StateFailed(parent=self.state_root)

    def enter_initial_state(self) -> None:
        self.state_current = self.state_idle
        self.observer.on_entry(self.name, "Root")
        self.state_root.on_entry(self)
        self.observer.on_entry(self.name, "Idle")
        self.state_idle.on_entry(self)

    def set_state(self, state_name: str) -> None:
        state_map = {
            "Idle": self.state_idle,
            "Active_WaitingBreakout": self.state_active_waiting_breakout,
            "Active_WaitingSignal": self.state_active_waiting_signal,
            "Active_WaitingEntry": self.state_active_waiting_entry,
            "Completed": self.state_completed,
            "Failed": self.state_failed,
        }
        if state_name in state_map:
            self.state_current = state_map[state_name]

    def on_strategy_created(self, strategy_id: str) -> None:
        if self.state_current:
            self.state_current.on_strategy_created(self, strategy_id)

    def on_price_breakout(self, price: float, direction: str) -> None:
        if self.state_current:
            self.state_current.on_price_breakout(self, price, direction)

    def on_signal_found(self) -> None:
        if self.state_current:
            self.state_current.on_signal_found(self)

    def on_order_filled(self) -> None:
        if self.state_current:
            self.state_current.on_order_filled(self)

    def on_strategy_completed(self) -> None:
        if self.state_current:
            self.state_current.on_strategy_completed(self)

    def on_strategy_failed(self) -> None:
        if self.state_current:
            self.state_current.on_strategy_failed(self)

    def on_ev_timeout(self, source: Any) -> None:
        if self.state_current:
            self.state_current.on_ev_timeout(self, source)


class StrategyFeeder:
    """Event feeder for BDBOStrategy. Provides typed event methods."""

    def __init__(self, context: BDBOStrategyContext):
        self.context = context

    def strategy_created(self, strategy_id: str) -> None:
        self.context.on_strategy_created(strategy_id)

    def price_breakout(self, price: float, direction: str) -> None:
        self.context.on_price_breakout(price, direction)

    def signal_found(self) -> None:
        self.context.on_signal_found()

    def order_filled(self) -> None:
        self.context.on_order_filled()

    def strategy_completed(self) -> None:
        self.context.on_strategy_completed()

    def strategy_failed(self) -> None:
        self.context.on_strategy_failed()

    def ev_timeout(self, source: Any) -> None:
        self.context.on_ev_timeout(source)

